/*
This file is auto-generated by OWL2Go (https://git.rwth-aachen.de/acs/public/ontology/owl/owl2go).

Copyright 2020 Institute for Automation of Complex Power Systems,
E.ON Energy Research Center, RWTH Aachen University

This project is licensed under either of
- Apache License, Version 2.0
- MIT License
at your option.

Apache License, Version 2.0:

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

MIT License:

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package input

import (
	"io"
	"strconv"
)

//GenerateInputFile generates the input file for the performance measurement
func GenerateInputFile(numClasses int, file io.Writer) (err error) {
	file.Write([]byte("@prefix test: <https://example.com/test#> .\n"))
	file.Write([]byte("@prefix owl: <http://www.w3.org/2002/07/owl#> .\n"))
	file.Write([]byte("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"))
	file.Write([]byte("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n"))
	file.Write([]byte("@base <https://example.com/test> .\n"))

	file.Write([]byte("<https://example.com/test> rdf:type owl:Ontology .\n"))

	file.Write([]byte("test:propa rdf:type owl:ObjectProperty .\n"))
	file.Write([]byte("test:propb rdf:type owl:ObjectProperty .\n"))

	file.Write([]byte("test:bclass rdf:type owl:Class ;\n"))
	file.Write([]byte("    rdfs:subClassOf [ rdf:type owl:Restriction ;\n"))
	file.Write([]byte("        owl:onProperty test:propa ;\n"))
	file.Write([]byte("        owl:allValuesFrom test:bclass\n"))
	file.Write([]byte("        ] ,\n"))
	file.Write([]byte("        [ rdf:type owl:Restriction ;\n"))
	file.Write([]byte("        owl:onProperty test:propb ;\n"))
	file.Write([]byte("        owl:allValuesFrom test:bclass\n"))
	file.Write([]byte("        ] .\n"))

	for i := 0; i < numClasses; i++ {
		className := "class" + strconv.Itoa(i) + "d"
		file.Write([]byte("test:" + className + " rdf:type owl:Class ;\n"))
		file.Write([]byte("    rdfs:subClassOf test:bclass .\n"))
	}
	return
}
